### PR TITLE
Change topic structure

### PR DESCRIPTION
**Pull request by ctron**
I did change the topic structure so that we have `/<sensor>/data/<metric>` now.

Would that be ok?

### CODE REVIEW

**Comment by lulf** [comment]
My only concern is that we have to create a toplevel (new broker) address for each sensor. Would it make sense to add a toplevel prefix in front? How about 

sensor/<sensor id>/data/<metric>

This also has a nice property of being able to receive metrics from all sensors by subscribing to sensor/# or sensor/+/data/temperature

**Comment by ctron** [comment]
That is a good idea. Can we still assign different credentials to different sub-topics then? So that sensor a cannot read/write from/to sensor b?

**Comment by lulf** [comment]
We don't have any authentication support in the current enmasse version, and I don't know if this is possible with hierarchal topics in Artemis. 

I agree that that is not ideal in a production setup perhaps, but I would say its OK for now until we get some experience playing around with this. What do you think?

**Comment by ctron** [comment]
Like that?

**Review by lulf — APPROVED** [review]

**Comment by lulf** [comment]
Looks good!

**Comment by jbtrystram** [comment]
:+1:

**Pull request merged**
